[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/bank-management-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
