name: CI/CD Pipeline for Bank Management

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: |
        docker build -t bank-management:latest .

    - name: Log in to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        docker tag bank-management:latest ${{ secrets.DOCKERHUB_USERNAME }}/bank-management:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-management:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to production
      run: echo "Deployment would happen here"
      # Add your deployment steps here, such as:
      # - SSH into your server
      # - Pull the latest Docker image
      # - Stop and restart the container
